/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
import java. util.*;
import javax.swing.JOptionPane;
import java.io.FileWriter;


/*
try{
                FileWriter myWriter = new FileWriter ("textlogin.text",true);
                myWriter .write(""+name+","+pass);
                myWriter .write(System.getProperty("line.separator"));
                myWriter .write(""+"//"+id+","+email+","+add+","+age+"//");
                myWriter .write(System.getProperty("line.separator"));
                myWriter .close();
                JOptionPane.showMessageDialog(null," Account Created , Now you can Login");
            
                
            }
            catch (Exception e){
                System.out.println("An error occurred.");
            } 
*/
public class addbook extends javax.swing.JFrame {
 
    
    public addbook() {
        initComponents();
        this. setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        book_title = new javax.swing.JLabel();
        edt_book_title = new javax.swing.JTextField();
        edt_edition = new javax.swing.JTextField();
        edt_publication = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        publication_year = new javax.swing.JLabel();
        edition = new javax.swing.JLabel();
        book_genre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edt_book_genre = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JLabel();
        edt_quantity = new javax.swing.JTextField();
        availability = new javax.swing.JLabel();
        available = new javax.swing.JRadioButton();
        not_available = new javax.swing.JRadioButton();
        author = new javax.swing.JLabel();
        edt_author = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        book_title.setText("Book Title:");

        edt_book_title.setForeground(new java.awt.Color(102, 102, 102));
        edt_book_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_book_titleActionPerformed(evt);
            }
        });

        edt_edition.setForeground(new java.awt.Color(102, 102, 102));
        edt_edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_editionActionPerformed(evt);
            }
        });

        edt_publication.setForeground(new java.awt.Color(102, 102, 102));
        edt_publication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_publicationActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(0, 102, 153));
        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("ADD");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        publication_year.setText("Publication Year:");

        edition.setText("edition:");

        book_genre.setText("Book Genre:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("ADD BOOK");

        edt_book_genre.setForeground(new java.awt.Color(102, 102, 102));
        edt_book_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science Fiction", "Romance", "Non Fiction", "Documentary", "Novel", "Thriller", "Biography" }));

        quantity.setText("Quantity:");

        availability.setText("Availability:");

        buttonGroup1.add(available);
        available.setText("Available");
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });

        buttonGroup1.add(not_available);
        not_available.setText("Not Available");
        not_available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                not_availableActionPerformed(evt);
            }
        });

        author.setText("Author:");

        edt_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_authorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(book_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edt_book_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edt_book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availability)
                                    .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edt_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(not_available, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(publication_year)
                                .addGap(18, 18, 18)
                                .addComponent(edt_publication, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edt_author, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_title)
                    .addComponent(edt_book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_genre)
                    .addComponent(edt_book_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(author)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(edt_author))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity)
                    .addComponent(edt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publication_year)
                    .addComponent(edt_publication, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edition)
                    .addComponent(edt_edition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availability)
                    .addComponent(available)
                    .addComponent(not_available))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edt_book_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_book_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_book_titleActionPerformed

    private void edt_editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_editionActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
if(!edt_book_title.getText().isEmpty() && !edt_quantity.getText().isEmpty()){
    String book_title= edt_book_title.getText();
    String book_genre=edt_book_genre.getSelectedItem().toString();
    String author=edt_author.getText();
    double quantity=Double.parseDouble(edt_quantity.getText());
    String publication_year=edt_publication.getText();
    double edition=Double.parseDouble(edt_edition.getText());
    String availability;
    if(available.isSelected()){
        availability="available";
        try {
    FileWriter myWriter = new FileWriter ("addbook.txt");
               myWriter.write("the added book information: ");
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("----------------------------------------");
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("book title: " + book_title);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("book genre: " + book_genre);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("book author: "+ author);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("Quantity: " + quantity);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("Publication Year: " +publication_year);
                myWriter .write(System.getProperty("line.separator"));
                 myWriter.write("Edition: " + edition);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("availability:"+ availability);
               
               myWriter.close();
               //JOptionPane.showMessageDialog(null," ");
            
                }
            catch (Exception e){
                System.out.println("An error occurred.");
            }
    }
    else{
        availability="not available";
      try {
    FileWriter myWriter = new FileWriter ("addbook.txt");
               myWriter.write("the added book information: ");
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("----------------------------------------");
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("book title: " + book_title);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("book genre: " + book_genre);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("book author: "+ author);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("Quantity: " + quantity);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("Publication Year: " +publication_year);
                myWriter .write(System.getProperty("line.separator"));
                 myWriter.write("Edition: " + edition);
                myWriter .write(System.getProperty("line.separator"));
               myWriter.write("availability:"+ availability);
               
               myWriter.close();
               //JOptionPane.showMessageDialog(null," ");
            
                }
            catch (Exception e){
                System.out.println("An error occurred.");
            }
    }
    
    
    JOptionPane.showMessageDialog(null,"The book was added successfully");
    this.dispose();
}
 // TODO add your handling code here:
    }//GEN-LAST:event_add_btnActionPerformed

    private void edt_publicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_publicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_publicationActionPerformed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableActionPerformed

    private void not_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_not_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_not_availableActionPerformed

    private void edt_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_authorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel author;
    private javax.swing.JLabel availability;
    private javax.swing.JRadioButton available;
    private javax.swing.JLabel book_genre;
    private javax.swing.JLabel book_title;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel edition;
    private javax.swing.JTextField edt_author;
    private javax.swing.JComboBox<String> edt_book_genre;
    private javax.swing.JTextField edt_book_title;
    private javax.swing.JTextField edt_edition;
    private javax.swing.JTextField edt_publication;
    private javax.swing.JTextField edt_quantity;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton not_available;
    private javax.swing.JLabel publication_year;
    private javax.swing.JLabel quantity;
    // End of variables declaration//GEN-END:variables
}
