import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Hossam
 */
public class Student_options extends javax.swing.JFrame {
    int studentno;
    int bookingcounter = 0;
    BookReservationcontroller control = new BookReservationcontroller();
    
    //same code of book for room/////////////  <-----------------
    /**
     * Creates new form Student_options
     */
    public Student_options(int in) {
        studentno=in;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bfeedback = new javax.swing.JButton();
        bdeleteroomres = new javax.swing.JButton();
        bresbook = new javax.swing.JButton();
        bsearchbook = new javax.swing.JButton();
        broomres = new javax.swing.JButton();
        bdeletebookingbook = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 8));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("How can we help you?");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bfeedback.setBackground(new java.awt.Color(0, 51, 51));
        bfeedback.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bfeedback.setForeground(new java.awt.Color(255, 255, 255));
        bfeedback.setText("Give feedback");
        bfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfeedbackActionPerformed(evt);
            }
        });

        bdeleteroomres.setBackground(new java.awt.Color(0, 51, 51));
        bdeleteroomres.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bdeleteroomres.setForeground(new java.awt.Color(255, 255, 255));
        bdeleteroomres.setText("Delete reservation");
        bdeleteroomres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteroomresActionPerformed(evt);
            }
        });

        bresbook.setBackground(new java.awt.Color(0, 51, 51));
        bresbook.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bresbook.setForeground(new java.awt.Color(255, 255, 255));
        bresbook.setText("Reserve a book");
        bresbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresbookActionPerformed(evt);
            }
        });

        bsearchbook.setBackground(new java.awt.Color(0, 51, 51));
        bsearchbook.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bsearchbook.setForeground(new java.awt.Color(255, 255, 255));
        bsearchbook.setText("Search for book");
        bsearchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchbookActionPerformed(evt);
            }
        });

        broomres.setBackground(new java.awt.Color(0, 51, 51));
        broomres.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        broomres.setForeground(new java.awt.Color(255, 255, 255));
        broomres.setText("Book a room");
        broomres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broomresActionPerformed(evt);
            }
        });

        bdeletebookingbook.setBackground(new java.awt.Color(0, 51, 51));
        bdeletebookingbook.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bdeletebookingbook.setForeground(new java.awt.Color(255, 255, 255));
        bdeletebookingbook.setText("Return book ");
        bdeletebookingbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeletebookingbookActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton8.setText("Sign out");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 51, 51));
        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Library management system");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(broomres, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(bfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton8)
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bsearchbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(bresbook, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bdeleteroomres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bdeletebookingbook, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bresbook, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdeletebookingbook, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(broomres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdeleteroomres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsearchbook, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bresbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresbookActionPerformed
        try{
        new Borrow_Book(studentno,bookingcounter).setVisible(true);
        bookingcounter++;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"error 404, code not found");
        }
    }//GEN-LAST:event_bresbookActionPerformed

    private void broomresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broomresActionPerformed
            //same code of book for room/////////////  <-----------------
        try{
        new Reserve_room (studentno,bookingcounter).setVisible(true);
        bookingcounter++;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"error 404, code not found");
        }
    
    }//GEN-LAST:event_broomresActionPerformed

    private void bdeletebookingbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeletebookingbookActionPerformed
        if(bookingcounter == 0){
            JOptionPane.showMessageDialog(null,"you havent booked any book yet");
        }
        else{
            try{
            int ans=Integer.parseInt(JOptionPane.showInputDialog("which booking do you want to delete (1) or (2)"));
            if(ans == 1){
                try{
                JOptionPane.showMessageDialog(null,"Booking deleted");
                bookingcounter--;
                }
                catch(Exception e){
            JOptionPane.showMessageDialog(null,"error 404, code not found");
        }
            }
            else if(ans == 2){
                try{
            JOptionPane.showMessageDialog(null,"Booking deleted");
                bookingcounter--;
                }
                catch(Exception e){
            JOptionPane.showMessageDialog(null,"error 404, code not found");
        }
            }
            }
            catch(IndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null,"input mismatch occured");
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"error occured");
            }
        }
    }//GEN-LAST:event_bdeletebookingbookActionPerformed

    private void bdeleteroomresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteroomresActionPerformed
// same code for deletion here ////////////////////// <---------------------------    
if(bookingcounter == 0){
            JOptionPane.showMessageDialog(null,"you havent booked any book yet");
        }
        else{
            try{
            int ans=Integer.parseInt(JOptionPane.showInputDialog("which booking do you want to delete (1) or (2)"));
            if(ans == 1){
                try{
                JOptionPane.showMessageDialog(null,"Booking deleted");
                bookingcounter--;
                }
                catch(Exception e){
            JOptionPane.showMessageDialog(null,"error 404, code not found");
        }
            }
            else if(ans == 2){
                try{
            JOptionPane.showMessageDialog(null,"Booking deleted");
                bookingcounter--;
                }
                catch(Exception e){
            JOptionPane.showMessageDialog(null,"error 404, code not found");
        }
            }
            }
            catch(IndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null,"input mismatch occured");
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"error occured");
            }
        }
    }//GEN-LAST:event_bdeleteroomresActionPerformed

    private void bfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfeedbackActionPerformed
        String value1 = JOptionPane.showInputDialog(this,"Enter ID ");
        String value = JOptionPane.showInputDialog(this,"Enter Your Feedback ");
        String ID = value1;               
        String fed = value;
        //if(ID.isEmpty()||fed.isEmpty()){
            try{
                FileWriter myWriter = new FileWriter ("feedback.text",true);
                myWriter .write(""+ID+" :"+fed);
                myWriter .write(System.getProperty("line.separator"));
                myWriter .close();
                JOptionPane.showMessageDialog(null," Feedback accepted ");
            
                
            }
            catch (Exception e){
                System.out.println("An error occurred.");
            }
//        } else {
//            JOptionPane.showMessageDialog(null," Canceled ");
//        }
//        
    }//GEN-LAST:event_bfeedbackActionPerformed

    private void bsearchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchbookActionPerformed
    try{
        control.searchmaterial();
    }
    catch (Exception ex) {
        System.out.println("Connect failed ! ");
        }
    }//GEN-LAST:event_bsearchbookActionPerformed
private boolean isbnExists(String isbnToCheck) {
    try (BufferedReader reader = new BufferedReader(new FileReader("addbook.txt"))) {
        String line;
        // Read each line of the file
        while ((line = reader.readLine()) != null) {
            if (line.startsWith("ISBN:")) {
                // Extract ISBN from the line
                String isbn = line.substring(6).trim();
                // Check if extracted ISBN matches the one to check
                if (isbn.equals(isbnToCheck)) {
                    return true; // ISBN exists
                }
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }
    return false; // ISBN does not exist
}
private String getName(String isbnToCheck) {
    String bname = null;
    try (BufferedReader reader = new BufferedReader(new FileReader("addbook.txt"))) {
        String line;
        // Read each line of the file
        while ((line = reader.readLine()) != null) {
            if (line.startsWith("ISBN:")) {
                // Extract isbn from the line
                String isbn = line.substring(6).trim();
                // Check if extracted ISBN matches the one to check
                if (isbn.equals(isbnToCheck)) {
                if(line.startsWith("Name")){
                bname = line.substring(0).trim();
                }       
                       
                       }
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }
return bname;
}

private void deleteBookEntry(String isbnToDelete) {
    // Define input and temporary files
    File inputFile = new File("addbook.txt");
    File tempFile = new File("temp.txt");

    try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
         BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

        String line;

        // Read each line of the input file
        while ((line = reader.readLine()) != null) {
            if (line.startsWith("ISBN:")) {
                // Extract ISBN from the line
                String isbn = line.substring(6).trim();
                // Skip the line if it matches the ISBN to delete
                if (isbn.equals(isbnToDelete)) {
                    continue;
                }
            }
            // Write the line to the temporary file
            writer.write(line + System.getProperty("line.separator"));
        }
    } catch (IOException ex) {
        // Show error message if deleting the book entry fails
        JOptionPane.showMessageDialog(this, "An error occurred while deleting the book entry.", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
        // Return from method
        return;
    }

    // Replace the original file with the temporary file
    if (!inputFile.delete()) {
        // Show error message if deleting the original file fails
        JOptionPane.showMessageDialog(this, "An error occurred while deleting the original file.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!tempFile.renameTo(inputFile)) {
        // Show error message if renaming the temporary file fails
        JOptionPane.showMessageDialog(this, "An error occurred while renaming the temporary file.", "Error", JOptionPane.ERROR_MESSAGE);
    }       
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Login_application signin = new Login_application();
        signin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Book.books.add(new Book(22, "intro to programming" , "Programming" , "no one" , 1 , true));
                Student.students.add(new Student("amr","maadi", "amr@bue", 236044 , "ics"));
                int i=0;
                new Student_options(i).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdeletebookingbook;
    private javax.swing.JButton bdeleteroomres;
    private javax.swing.JButton bfeedback;
    private javax.swing.JButton bresbook;
    private javax.swing.JButton broomres;
    private javax.swing.JButton bsearchbook;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
